### PR TITLE
Adding agavi, mojavi, prado

### PR DESCRIPTION
**Pull request by harikt**
if I am correct I have read some where about the history of symfony was evolved from mojavi and prado. Mojavi seems moved to agavi later.

Also symfony was released in 2005.

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones not sure whether you are adding only the frameworks you have came across. If not, a few ones I know.

**Comment by harikt** [comment]
Prado seems changed as Yii. I am looking the author ( @qiangxue ) https://web.archive.org/web/20041209062615/http://www.zend.com/php5/contest/contest.php?id=36&single=1  . 

May be the developers part away?

**Comment by samdark** [comment]
### Prado

First version of PRADO was released in June 2004 using PHP4. Indeed, the author was @qiangxue. Originally it was inspired by Apache Tapestry and many ideas were borrowed from Borland Delphi and Microsoft ASP.NET.

Then there was Zend PHP 5 coding contest (gophp5) and @qiangxue rewrote PRADO in PHP 5. Project won the context.

The project was hosted at SourceForge. In mid 2005 @xwz contributed i18n and l10n resulting in 2.0 release.

In May 2005 it was decided to rewrite the project incorporating new stuff from Microsoft ASP.NET 2.0. In April 2006 version 3.0 was released. Starting from 3.0 the focus was on quality and stability.

Prado is still alive and used by many people.

### Yii

In October 2006 @qiangxue [announced Yii alpha](http://www.pradosoft.com/forum/index.php?topic=11022.0) at PRADO forums.

In December 3rd 2008 1.0.0 was released. Many things were adopted from PRADO such as ActiveRecord, i18n, l10n etc. Other sources of inspiration were RoR (convention over configuration, some AR features), symfony1 (filters and plugins) and Joomla (modules and message translation).

Yii 1.0.0 was way faster than anything with such capabilities out there so it got huge community quite fast.

Yii 1.1 was released in January 2010 featuring form builder, relational queries for AR, pre-defined phpunit bootstrap etc.

I've joined core team in 2010. By the end of the year we've started discussing Yii 1.2.0 while actively developing 1.1 branch. By may of 2011 it was decided to adopt modern tech and fix architectural mistakes moving straight to 2.0. First commit to secret git repo was made.

In May 2013 we've released first public preview of Yii 2.0. In October 2014 Yii 2.0 final was released.

**Comment by pmjones** [comment]
Adding the links and dates for Prado and Yii release announcements would be much appreciated.

**Pull request merged**
